[package]
name = "pyxirr"
version = "0.1.0"
authors = ["Anexen <avolk93@gmail.com>"]
edition = "2018"

[lib]
name = "pyxirr"
crate-type = ["cdylib"]

[dependencies]
xirr = "0.2.2"
pyo3 = { version = "0.10.1", features = ["extension-module"] }
chrono = "0.4.11"
